In [47]:
import pandas as pd
from pathlib import Path

#Load File

current_data = Path('Data/alt_fuel_stations.csv')

#Convert data to dataframe with Pandas

current_df = pd.read_csv(current_data)

current_df.head()

C:\Users\Alex\AppData\Local\Temp\ipykernel_14072\584244766.py:10: DtypeWarning: Columns (6,15,16,20,31,33,34,35,36,43,46,49,52,53,56,57,58,59,60,61,62,65,67,69,70,71) have mixed types. Specify dtype option on import or set low_memory=False.
  current_df = pd.read_csv(current_data)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,...,Restricted Access,RD Blends,RD Blends (French),RD Blended with Biodiesel,RD Maximum Biodiesel Level,NPS Unit Name,CNG Station Sells Renewable Natural Gas,LNG Station Sells Renewable Natural Gas,Maximum Vehicle Class,EV Workplace Charging
0,CNG,Spire - Montgomery Operations Center,2951 Chestnut St,NaN,Montgomery,AL,36107,NaN,NaN,E,...,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,MD,NaN
1,CNG,Metropolitan Atlanta Rapid Transit Authority,2424 Piedmont Rd NE,NaN,Atlanta,GA,30324,NaN,NaN,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LD,NaN
2,CNG,United Parcel Service,270 Marvin Miller Dr,NaN,Atlanta,GA,30336,NaN,NaN,E,...,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,HD,NaN
3,CNG,Arkansas Oklahoma Gas Corp,2100 S Waldron Rd,NaN,Fort Smith,AR,72903,NaN,479-783-3181,E,...,False,NaN,NaN,NaN,NaN,NaN,False,NaN,MD,NaN
4,CNG,Clean Energy - Logan International Airport,1000 Cottage St Ext,"From Route 1, take the first exit after Callah...",East Boston,MA,2128,NaN,866-809-4869,E,...,False,NaN,NaN,NaN,NaN,NaN,True,NaN,MD,NaN

In [48]:
#Remove unwanted columns

to_drop = ['Station Name', 'Street Address', 'Intersection Directions', 'City', 'ZIP', 'Plus4', 
           'Station Phone', 'Status Code', 'Restricted Access', 'RD Blends', 'RD Blends (French)', 
           'RD Blended with Biodiesel', 'RD Maximum Biodiesel Level', 'NPS Unit Name', 
           'CNG Station Sells Renewable Natural Gas', 'LNG Station Sells Renewable Natural Gas', 
           'Maximum Vehicle Class', 'EV Workplace Charging', 'Expected Date', 'Groups With Access Code', 
           'Access Days Time', 'Cards Accepted', 'BD Blends', 'NG Fill Type Code', 'NG PSI', 'EV Pricing', 
           'EV Pricing (French)', 'LPG Nozzle Types', 'Hydrogen Pressures', 'Hydrogen Standards', 'CNG Fill Type Code', 
           'CNG PSI', 'CNG Vehicle Class', 'LNG Vehicle Class', 'EV On-Site Renewable Source', 'EV Other Info', 
           'Geocode Status', 'Access Code', 'Access Detail Code', 'Federal Agency Code', 'Facility Type', 
           'CNG Total Compression Capacity', 'CNG Storage Capacity', 'LNG On-Site Renewable Source', 'EV Network', 
           'Country', 'Date Last Confirmed', 'EV Connector Types', 'Intersection Directions (French)', 
           'Access Days Time (French)', 'BD Blends (French)', 'Groups With Access Code (French)', 'EV Level1 EVSE Num', 
           'EV Level2 EVSE Num', 'EV DC Fast Count', 'EV Network Web', 'ID', 'Updated At', 'Federal Agency ID', 
           'Federal Agency Name', 'Open Date', 'Hydrogen Status Link', 'NG Vehicle Class', 'LPG Primary', 'E85 Blender Pump', 
           'Hydrogen Is Retail', 'CNG On-Site Renewable Source', 'E85 Other Ethanol Blends', 'Owner Type Code', 'Latitude', 
           'Longitude', 'CNG Dispenser Num']

current_df = current_df.drop(to_drop, axis = 1)

In [49]:
#Confirm Column Drop

current_df.head()

  Fuel Type Code State
0            CNG    AL
1            CNG    GA
2            CNG    GA
3            CNG    AR
4            CNG    MA

In [50]:
#Group fuel types and assign by state

totals_df = current_df.groupby('State')['Fuel Type Code'].value_counts().unstack(fill_value = 0)


totals_df.head()

Fuel Type Code  BD  CNG  E85   ELEC  HY  LNG  LPG   RD
State
AK               0    0    0     67   0    0    1    0
AL              10   30   37    463   0    3   61    0
AR              35   14   74    342   0    0   34    0
AZ              77   27   21   1322   0    5   72    0
CA              48  302  374  17905  93   40  253  601

In [51]:
#Export new data frame

totals_df.to_csv('Current_Alt_Fuel_stations.csv')